#!/usr/bin/python

import sys
import re
import markdown
from markdown.treeprocessors import Treeprocessor
from markdown.postprocessors import Postprocessor
from markdown.extensions import Extension
import xml.etree.ElementTree as ET

import markdown
from markdown.treeprocessors import Treeprocessor
from markdown.extensions import Extension
import xml.etree.ElementTree as ET

class SectionWrapperProcessor(Treeprocessor):
  def run(self, root):
    # Create a new blank root element to hold our restructured tree
    new_root = ET.Element(root.tag, root.attrib)
    slide_num = 0;
    anim_num = 0;

    # Start the very first section container
    current_section = ET.SubElement(new_root, 'section', {'class': 'slide title'})
    current_div = ET.SubElement(current_section, 'div', {'id': f'slide{slide_num}' } )

    # Iterate through all top-level child elements of the flat markdown output
    for child in list(root):
      if child.tag == 'hr':
        slide_num += 1
        anim_num = 0
        current_section = ET.SubElement(new_root, 'section', {'class': 'slide'})
        current_div = ET.SubElement(current_section, 'div', {'id': f'slide{slide_num}' } )
      elif child.tag == 'p' and child.text and child.text.strip() == '--':
        anim_num += 1
        current_div = ET.SubElement(current_section, 'div', {'id': f'slide{slide_num}-{anim_num}' } )
      else:
        current_div.append(self.add_style (current_div, child))

    # Replace the contents of the old flat root with our newly structured tree
    root.clear()
    root.text = new_root.text
    root.tail = new_root.tail
    root.extend(list(new_root))
    return root

  def parse_style (self, text):
    if text and text.startswith('@'):
      lines = text.splitlines()
      text = '\n'.join (lines[1:]) if len(lines)>1 else None

      style = lines[0][1:].strip()

      pattern = r'"([^"]*)"'
      match = re.search(pattern, style)
      tag = match.group(1) if match else None
      style = re.sub(r'\s*"[^"]*"\s*', '', style).strip()

      pattern = r'\[([^\]]*)\]'
      match = re.search(pattern, style)
      pos = match.group(1) if match else None
      cl = re.sub(r'\s*\[[^\]]*\]\s*', '', style).strip()
      if cl is not None and len(cl) == 0:
        cl = None

      return ( text, cl, tag, pos )
    return ( text, None, None, None )

  def update_style (self, node, cl, tag, pos):
    if cl: node.set ('class', cl)
    if tag: node.set ('data-tag', tag)
    if pos:
      if any (m in pos for m in ['left', 'right', 'top', 'bottom']):
        pos = 'position: absolute; ' + pos
      node.set ('style', pos)

  def add_style (self, parent, node):

    node.text, cl, tag, pos = self.parse_style (node.text)

    if parent.tag == 'blockquote' and node.tag == 'p':
      self.update_style (parent, cl, tag, pos)
    elif parent.tag == 'p' and ( node.tag == 'pre' or node.tag == 'img' ):
      for attr in ( 'class', 'style', 'data-tag' ):
        if parent.get(attr):
          node.set (attr, parent.get(attr))
          parent.attrib.pop (attr, None)
    else:
      self.update_style (node, cl, tag, pos)

    for child in list(node):
      self.add_style (node, child)

    return node


class SectionWrapperExtension(Extension):
  def extendMarkdown(self, md):
    # Register the processor with high priority so it runs right after the tree is built
    md.treeprocessors.register(SectionWrapperProcessor(md), 'section_wrapper', 0)






def move_attributes(match):
  attributes = match.group(1)
  # Return the clean swap: place the attributes onto the <pre> tag instead
  return f'<pre{attributes}>'


class PreTagStyleFixer(Postprocessor):
  def run(self, html_text):
    """
    Regex looks for pairs like: <pre><code class="custom-class" style="border: 1px;">
    And transforms them to:    <pre class="custom-class" style="border: 1px;"><code>
    """
    # Matches <pre> followed immediately by <code ...>
    # Group 1: Everything inside the <code> tag attributes (class, style, id, etc.)
    pattern = re.compile(r'<p([^>]*)></p>\n<pre>')

    return pattern.sub(move_attributes, html_text)

class ClearPreStylesExtension(Extension):
  def extendMarkdown(self, md):
    # Register the postprocessor to run at the absolute end of compilation
    md.postprocessors.register(PreTagStyleFixer(md), 'pre_style_fixer', 0)













########################################
#        Run conversion
########################################

fm = {}
with open (sys.argv[1], 'r') as fd:
  line = fd.readline().rstrip()
  if line == '---':
    while True:
      line = fd.readline().rstrip()
      if line == '---': break;
      key, value = line.split(':', maxsplit=1)
      fm[key.strip()] = value.strip()

  md_text = fd.read()

# Compile the Markdown with our custom extension
contents = markdown.markdown(md_text, extensions=['fenced_code', SectionWrapperExtension(), ClearPreStylesExtension()])


template = open(sys.argv[2], 'r', encoding='utf-8').read()

with open(sys.argv[3], 'w', encoding='utf-8') as fd:
  for k,v in fm.items():
    template = template.replace(f'##{k.upper()}##', v)
  fd.write (template.replace ('##CONTENT##', contents))



